version: '3'
services:
  vdr:
    build: vdr
    devices:
      - "/dev/dvb:/dev/dvb"
    volumes:
      - ./recordings:/recordings
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./timers.conf:/etc/vdr/timers.conf
      - ./svdrphosts.conf:/etc/vdr/svdrphosts.conf
    ports:
      - "3001:3000"
      - "8008:8008"
      - "34890:34890"
      - "6419:6419"
    tty: true
    restart: always
    
