version: '3'
services:
  vdr:
    build: vdr
    devices:
      - "/dev/dvb:/dev/dvb"
    volumes:
      - /srv/recordings:/recordings
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./timers.conf:/etc/vdr/timers.conf
    ports:
      - "3001:3000"
      - "8008:8008"
      - "34890:34890"
    tty: true
    
